Algoritmo "Atividade04 - Problema 07"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/11/2021
Var
// Seção de Declarações das variáveis 
nome:caracter
endereco:caracter
telefone:caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite seu nome :")
leia(nome)
escreval("Digite seu endereço :")
leia(endereco)
escreval("Digite seu telefone :")
leia(telefone)

escreval("Meu nome é : ",nome)
escreval("Meu endereço é :",endereco)
escreval("Meu telefone é :",telefone)

Fimalgoritmo