Algoritmo "LISTA07Q9"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Walbert Monteiro
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/12/2021
Var
// Seção de Declarações das variáveis 
cont, num, i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

cont<-0
num<-5

enquanto (num<=500) faca
     cont<-cont+1
     escreva(num)
     num<-num+5
fimenquanto

escreval()
escreval("O total de numeros calculados foram:", cont)

Fimalgoritmo