Algoritmo "Atividade04-Problema02"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : albert Monteiro
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Walbert
// Data atual  : 29/11/2021
Var
// Seção de Declarações das variáveis 
lado, area, perimetro: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

//Solicitar dados
Escreva("Digite o valor do lado do quadrado: ")
leia(lado)

area<-lado*lado
perimetro<-4*lado

//Imprimir
Escreval("")
Escreval("O valor do lado do quadrado é: ", lado)
Escreval("O valor do perimetro para o quadrado é: ", perimetro)
Escreval("O valor da área do quadrado é: ", area)


Fimalgoritmo