Algoritmo "LISTA07Q2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Walbert Monteiro
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Walbert
// Data atual  : 19/12/2021
Var
// Seção de Declarações das variáveis 
valor01:inteiro
contador:inteiro
resultado:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Digite o valor para gerar a tabuada:")
leia(valor01)

contador <- 1

enquanto (contador<11) faca
 resultado <- contador * valor01
 escreval(valor01, " * ",contador, "=", resultado)
 contador <- contador +1
fimenquanto



Fimalgoritmo