Algoritmo "LISTA07Q08"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Walbert Monteiro
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Walbert
// Data atual  : 20/12/2021
Var
// Seção de Declarações das variáveis 
vl:real
x,n:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
vl<-0
n<-100

para x de 1 ate n faca
     //x<-n
     vl<-RaizQ(n)
     escreva(vl)
     n <- n+x
fimpara

Fimalgoritmo