Algoritmo "LISTA07Q05"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Walbert Monteiro
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Walbert
// Data atual  : 20/12/2021
Var
// Seção de Declarações das variáveis 
x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para x de 1 ate 20 faca
     escreva(x)
fimpara

Fimalgoritmo