Algoritmo "Atividade04-Problema03"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Walbert Monteiro
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Walbert
// Data atual  : 29/11/2021
Var
// Seção de Declarações das variáveis 
base:real
altura:real
area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o valor da base :")
leia(base)

escreval("Digite o valor da altura :")
leia(altura)

//Calculo da area do triangulo
area <-(base * altura)/2

escreval("O valor da área é :", area)

Fimalgoritmo