Algoritmo "LISTA07Q07"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Walbert Monteiro
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Walbert
// Data atual  : 20/12/2021
Var
// Seção de Declarações das variáveis 
x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para x de 20 ate 1 passo -1 faca
     x<-(x*x)
     escreva(x)
fimpara

Fimalgoritmo